--- 
title: "Bookdown TP Cours R"
author: "Svetlana et Simon L"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
---

# Introduction {#welcome}

## Objectifs de la démarche

Cette page a pour fonction de présenter les données de consommation énergétique, de production de nourriture et la population mondiale selon plusieurs critères.

Nous verrons dans un premier temps les données à l'échelle mondiale afin de visualiser la situation dans son ensemble au cours du temps.

Ensuite, nous entrerons dans le détail en ayant une vue continent par continent sur les mêmes éléments selon les années.

L'application shiny qui suit présentera le détail, pays par pays.

Nous visualiserons ensuite une vue cartographiée de l'année 2019 des totaux de consommation d'énergie, de production de nourriture ainsi que la population.

Enfin, une application shiny permettra de visualiser ces cartes selon l'année sélectionnée par l'utilisateur.

## Présentation des données 

Nous avons obtenu nos données des bases de données suivantes:

- Données temporelles de la population mondiale (WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xls) https://population.un.org/wpp/Download/Standard/Population/ Ce tableau contient les données de la population en millier de millions d’individus. Nous n’utiliserons que la feuille ESTIMATES.

- Données temporelles de consommation énergétique (owid-energy-data__OWID) https://ourworldindata.org/grapher/global-energy-substitution?country=~OWID_WRL

- Données temporelles de production de nourriture
(Production_Crops_Livestock_E_All_Data.csv)
https://www.fao.org/faostat/en/#data/QCL

Les codes iso des pays sont issus du package "countrycode" et les données géographiques des pays sont obtenues via le package "ggthemes"
