# Analyse mondiale

Cette page présente l'analyse à l'échelle mondiale au fur et à mesure des années.

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	fig.path = "Figures/",
	fig.retina = 3,
	message = FALSE,
	warning = FALSE
)
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(tidyselect)
library(readxl)
library(ggthemes)
library(countrycode)
library(ggthemes)
library(gapminder)


```


```{r}
energy<-read_delim("owid-energy-data__OWID.csv") |> 
  select(2,3,ends_with("consumption")) |> 
  filter(year>=1950) |>
  select(-5,-8,-12,-13) |> 
  pivot_longer(cols = c(3:11),
               names_to = "consumption_source",
               values_to = "energy_value") |> 
  mutate(consumption_type=if_else(consumption_source=="coal_consumption"|
                                    consumption_source=="oil_consumption"|
                                    consumption_source=="gas_consumption",
                                  "fossil_fuel_consumption",
                                  "low_carbon_consumption"),
         .after=year)



food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding = "ISO-8859-1")) |> 
  select(!ends_with("F")) |> 
  rename_with(~ str_remove(., "Y"), everything()) |> 
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary"))|> 
  pivot_longer(cols=8:67,
               names_to="year",
               values_to="food_value") |>  
  filter(Element=="Production") |> 
  mutate(year=as.numeric(year)) |> 
  select(2,4,8,9) |> 
  mutate(food_value=food_value/1000000)


population<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx",range="A17:BZ306",na="...") |> 
  select(1:3,Type,"1950":"2020") |> 
  pivot_longer(cols=5:75,
               names_to="year",
               values_to = "population") |> 
  mutate(population=population*1000) |> 
  rename(region=3) |> 
  mutate(year=as.numeric(year)) |> 
  select(3,5,6)


```



## Consommation d'énergie annuelle mondiale par type d'énergie

```{r}

energy_world<-energy |> 
  filter(country=="World")

ggplot(energy_world)+
  aes(year,energy_value,fill=consumption_type)+
  geom_col()+
  labs(title="Consommation annuelle mondiale par type d'énergie",x="Année",y="Consommation en ?")+
  scale_x_continuous(limits=c(1965,2020),
                     breaks=seq(1960,2020,10))+
   scale_y_continuous(limits=c(0,175000),
                     breaks=seq(0,175000,25000),
                     labels=function(x) {
    format(x,scientific=FALSE,big.mark=" ")
  })+
  theme_classic()+
  theme(axis.text.x=element_text(size=8,
                                 angle=45,
                                 hjust=1,
                                 vjust=1))
```

## Consommation d'énergie annuelle mondiale par source d'énergie

```{r}

ggplot(energy_world)+
  aes(year,energy_value,fill=consumption_source,group=consumption_type)+
  geom_col()+
  facet_grid(~consumption_type)+
  labs(title="Consommation annuelle mondiale par source d'énergie",x="Année",y="Consommation en ?")+
  scale_x_continuous(limits=c(1965,2020),
                     breaks=seq(1960,2020,10))+
  scale_y_continuous(limits=c(0,150000),
                     breaks=seq(0,150000,25000),
                     labels=function(x) {
    format(x,scientific=FALSE,big.mark=" ")
  })+
  theme_classic()+
  theme(axis.text.x=element_text(size=8,
                                 angle=45,
                                 hjust=1,
                                 vjust=1))
  
```

## Production annuelle mondiale de nourriture

```{r}
food<-read_delim("Production_Crops_Livestock_E_All_Data.csv") |> 
  select(!ends_with("F")) |> 
  rename_with(~ str_remove(., "Y"), everything()) |> 
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary"))|> 
  pivot_longer(cols=8:67,
               names_to="year",
               values_to="food_value") |>  
  filter(Element=="Production") |> 
  mutate(year=as.numeric(year)) |> 
  rename(Area_Code="Area Code") |> 
  rename(Item_Code="Item Code") |> 
  rename(Element_Code="Element Code") |> 
  mutate(food_value=food_value/1000000)

food_world<- food |> 
  filter(Area=="World") 
  

ggplot(food_world)+
  aes(year,food_value,fill=Item)+
  geom_col()+
  labs(title="Production annuelle mondiale par type d'aliment",x="Année",y="Production de nourriture (Mt)")+
  scale_x_continuous(limits=c(1960,2020),
                     breaks=seq(1960,2020,10))+
  scale_y_continuous(limits=c(0,10000),
                     breaks=seq(0,10000,1000))+
  theme_classic()+
  theme(axis.text.x=element_text(size=8,
                                 angle=45,
                                 hjust=1,
                                 vjust=1))
  
```

## Evolution de la population mondiale annuelle

```{r}

population_world<-population |> 
  filter(region=="WORLD") 

ggplot(population_world)+
  aes(year,population)+
  geom_col()+
    labs(title="Evolution de la population mondiale annuelle",x="Année",y="Population")+
     scale_x_continuous(limits=c(1950,2020),
                     breaks=seq(1950,2020,10))+
    scale_y_continuous(limits=c(0,8000000000),
                     breaks=seq(0,8000000000,1000000000),
                     labels=function(x) {
    format(x,scientific=FALSE,big.mark=" ")
  })+ 
  theme_classic()+
  theme(axis.text.x=element_text(size=8,
                                 angle=45,
                                 hjust=1,
                                 vjust=1))
 

```




  
